// <auto-generated />
using Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(LContext))]
    [Migration("20201020124616_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Model.Users.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("UserCode")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Usr_UserInfo");
                });

            modelBuilder.Entity("Domain.Model.Users.UserInfo", b =>
                {
                    b.OwnsMany("Domain.Model.Users.UserAddress", "UserAddresses", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("AddressTitle")
                                .HasColumnName("AddressTitle")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Area")
                                .HasColumnName("Area")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("City")
                                .HasColumnName("City")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Country")
                                .HasColumnName("Country")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Province")
                                .HasColumnName("Province")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Street")
                                .HasColumnName("Street")
                                .HasColumnType("nvarchar(200)");

                            b1.Property<int>("UserInfoId")
                                .HasColumnType("int");

                            b1.Property<string>("ZIP")
                                .HasColumnName("ZIP")
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("UserInfoId");

                            b1.ToTable("Usr_UserAddress");

                            b1.WithOwner()
                                .HasForeignKey("UserInfoId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
